# General
spring.application.name=consumer
application.admin.url=${APPLICATION_URL:http://localhost:8000}
application.keyword.service.url=${APPLICATION_KEYWORD_SERVICE_URL:https://cognitube-keyword-service.thankfulfield-7c1523f0.eastus.azurecontainerapps.io/api}
application.transcoding.service.url=${APPLICATION_TRANSCODING_SERVICE_URL:http://localhost:9032/api}
application.audio.conversion.job.image=${AUDIO_JOB_IMAGE:haozhealexzhang/cognitube-audio-conversion-job:latest}

# DB
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cog_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:cog_dev}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}

# Azure blob
azure.storage.connection-string=${AZURE_STORAGEBLOB_CONNECTIONSTRING:DefaultEndpointsProtocol=https;AccountName=cognitube;AccountKey=a1XDmr4IlO9I/tcsuh1akTaGFgmp+nQEoQdA8SlFpmmn7Zi0HKeDMk3ntxWjGI/HMFpQjzBys2ZX+AStqYVfsg==;BlobEndpoint=https://cognitube.blob.core.windows.net/;FileEndpoint=https://cognitube.file.core.windows.net/;TableEndpoint=https://cognitube.table.core.windows.net/;QueueEndpoint=https://cognitube.queue.core.windows.net/}
azure.storage.container-name-temp-video-container=${AZURE_STORAGE_CONTAINER_NAME_TEMP_VIDEO:private-container}
azure.storage.container-name-video-container=${AZURE_STORAGE_CONTAINER_NAME_VIDEO:video-container}
azure.storage.container-name-image-container=${AZURE_STORAGE_CONTAINER_NAME_IMAGE:image-container}
azure.storage.container-name-subtitle-container=${AZURE_STORAGE_CONTAINER_NAME_SUBTITLE:subtitle-container}
azure.storage.container-name-keywords-container=${AZURE_STORAGE_CONTAINER_NAME_KEYWORDS:keywords-container}
azure.storage.container-name-profile-image-container=${AZURE_STORAGE_CONTAINER_NAME_PROFILE_IMAGE:profile-image-container}
azure.storage.container-name-audio-container=${AZURE_STORAGE_CONTAINER_NAME_AUDIO:audio-container}
azure.storage.blob.endpoint=${AZURE_STORAGE_BLOB_ENDPOINT:https://cognitube.blob.core.windows.net}
azure.frontdoor.url=${AZURE_FRONTDOOR_URL:https://cognitube-hfegcsabcrgybtcw.z01.azurefd.net}

# Azure batch
azure.batch.account-name=${AZURE_BATCH_ACCOUNT_NAME:audio}
azure.batch.account-key=${AZURE_BATCH_ACCOUNT_KEY:VTx4AVW1yR+rh5TCN8qJsoToOV/oiXpcDmiXTAs1GCO4kb48xuyph1YNQzxzZADIDCq3GGRsewnL+ABaDUlg4Q==}
azure.batch.account-url=${AZURE_BATCH_ACCOUNT_URL:https://audio.eastus.batch.azure.com}

# Redis
spring.data.redis.host=${SPRING_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}
spring.data.redis.ssl.enabled=${SPRING_REDIS_USE_SSL:false}
spring.data.redis.password=${SPRING_REDIS_PASSWORD:}
spring.data.redis.database=${SPRING_REDIS_DATABASE:0}

# Kafka general
kafka.eventhub.namespace=${KAFKA_EVENTHUB_NAMESPACE:cognitube-kafka}
kafka.username=${KAFKA_EVENTHUB_USERNAME:\$ConnectionString}
kafka.password=${AZURE_EVENTHUB_CONNECTIONSTRING:Endpoint=sb://cognitube-kafka.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=l9+PMVbv8R4LuCtQlPo5x8PIE8jZqn8O4+AEhEMQoqA=}

# Video process consumer
kafka.video.process.topic=${KAFKA_VIDEO_PROCESS_TOPIC:video-process-test}
kafka.video.process.group.id=${KAFKA_VIDEO_PROCESS_GROUP_ID:video-process-group}
kafka.video.reencode.topic=${KAFKA_VIDEO_REENCODE_TOPIC:video-reencode-test}
kafka.video.ai.topic=${KAFKA_VIDEO_AI_TOPIC:video-ai-test}

# Encoding
application.encoding.default.audio.bit.rate.kbps=${DEFAULT_AUDIO_BIT_RATE_KBPS:16}
application.encoding.default.sampling.rate=${DEFAULT_SAMPLING_RATE:8000}