# General
spring.application.name=consumer
application.admin.url=${APPLICATION_URL:http://localhost:8000}

# DB
spring.datasource.url=jdbc:postgresql://postgres:5432/cog_db
spring.datasource.username=cog_dev
spring.datasource.password=password

# Azure blob
azure.storage.connection-string=${AZURE_STORAGEBLOB_CONNECTIONSTRING:DefaultEndpointsProtocol=https;AccountName=cognitube;AccountKey=a1XDmr4IlO9I/tcsuh1akTaGFgmp+nQEoQdA8SlFpmmn7Zi0HKeDMk3ntxWjGI/HMFpQjzBys2ZX+AStqYVfsg==;BlobEndpoint=https://cognitube.blob.core.windows.net/;FileEndpoint=https://cognitube.file.core.windows.net/;TableEndpoint=https://cognitube.table.core.windows.net/;QueueEndpoint=https://cognitube.queue.core.windows.net/}
azure.storage.container-name-temp-video-container=${AZURE_STORAGE_CONTAINER_NAME_TEMP_VIDEO:private-container}
azure.storage.container-name-video-container=${AZURE_STORAGE_CONTAINER_NAME_VIDEO:video-container}
azure.storage.container-name-image-container=${AZURE_STORAGE_CONTAINER_NAME_IMAGE:image-container}
azure.storage.container-name-subtitle-container=${AZURE_STORAGE_CONTAINER_NAME_SUBTITLE:subtitle-container}
azure.storage.container-name-keywords-container=${AZURE_STORAGE_CONTAINER_NAME_KEYWORDS:keywords-container}
azure.storage.container-name-profile-image-container=${AZURE_STORAGE_CONTAINER_NAME_PROFILE_IMAGE:profile-image-container}
azure.frontdoor.url=${AZURE_FRONTDOOR_URL:https://cognitube-hfegcsabcrgybtcw.z01.azurefd.net}

# Kafka general
kafka.eventhub.namespace=${KAFKA_EVENTHUB_NAMESPACE:cognitube-kafka}
kafka.username=${KAFKA_EVENTHUB_USERNAME:\$ConnectionString}
kafka.password=${AZURE_EVENTHUB_CONNECTIONSTRING:Endpoint=sb://cognitube-kafka.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=l9+PMVbv8R4LuCtQlPo5x8PIE8jZqn8O4+AEhEMQoqA=}

# Video process consumer
kafka.video.process.topic=${KAFKA_VIDEO_PROCESS_TOPIC:video-process-test}
kafka.video.process.group.id=${KAFKA_VIDEO_PROCESS_GROUP_ID:video-process-group}