name: Trigger auto deployment for cognitube-kafka-consumers

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/cognitube-kafka-consumers-AutoDeployTrigger-e5a6a48d-e846-47cd-b38d-8bff8eff8ba4.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.COGNITUBEKAFKACONSUMERS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.COGNITUBEKAFKACONSUMERS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.COGNITUBEKAFKACONSUMERS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: cogregdev.azurecr.io
          registryUsername: ${{ secrets.COGNITUBEKAFKACONSUMERS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.COGNITUBEKAFKACONSUMERS_REGISTRY_PASSWORD }}
          containerAppName: cognitube-kafka-consumers
          resourceGroup: cognitube-dev
          imageToBuild: cogregdev.azurecr.io/cognitube-kafka-consumers:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


